//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceRecord
    {
        public int Member_ID { get; set; }
        public int Event_ID { get; set; }
        public System.DateTime SwipeTime { get; set; }
        public bool isExcusedAbsence { get; set; }
    
        public virtual BYXEvent BYXEvent { get; set; }
        public virtual Member Member { get; set; }
    }
}
