//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BYXEvent
    {
        public BYXEvent()
        {
            this.AttendanceRecords = new HashSet<AttendanceRecord>();
        }
    
        public int Event_ID { get; set; }
        public System.DateTime Event_StartDateTime { get; set; }
        public string Event_Name { get; set; }
        public int EventType_ID { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<AttendanceRecord> AttendanceRecords { get; set; }
        public virtual EventType EventType { get; set; }
    }
}
