//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConMan
    {
        public int ID { get; set; }
        public string HTML { get; set; }
        public System.DateTime LastEditedOn { get; set; }
        public string LastEditedBy { get; set; }
    }
}
