//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventType
    {
        public EventType()
        {
            this.BYXEvents = new HashSet<BYXEvent>();
        }
    
        public int EventType_ID { get; set; }
        public int EventType_Weight { get; set; }
        public string EventType_Name { get; set; }
    
        public virtual ICollection<BYXEvent> BYXEvents { get; set; }
    }
}
