//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardianType
    {
        public int GuardianType_ID { get; set; }
        public string GuardianType_Label { get; set; }
    
        public virtual Guardian Guardian { get; set; }
    }
}
