//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.AttendanceRecords = new HashSet<AttendanceRecord>();
        }
    
        public int Member_ID { get; set; }
        public string Member_FirstName { get; set; }
        public string Member_LastName { get; set; }
        public string Member_EmailAddress { get; set; }
        public long Member_BannerID { get; set; }
        public int MemberType_ID { get; set; }
        public bool Deleted { get; set; }
        public Nullable<long> Member_IgnitedNum { get; set; }
    
        public virtual ICollection<AttendanceRecord> AttendanceRecords { get; set; }
        public virtual MemberType MemberType { get; set; }
    }
}
